#!/bin/bash
NAME=template
DIR=/home/ubuntu/template.be
USER=ubuntu
GROUP=ubuntu
WORKERS=4
WORKER_CLASS=uvicorn.workers.UvicornWorker
VENV=$DIR/venv/bin/activate
BIND=unix:$DIR/run/gunicorn.sock
LOG_LEVEL=info

cd $DIR
source $VENV

exec $DIR/venv/bin/gunicorn app.main:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --group=$GROUP \
  --bind=127.0.0.1:3000 \
  --log-level=$LOG_LEVEL \
  --access-logfile - \
  --error-logfile - 
 
# sudo supervisorctl restart template